from __future__ import annotations

QUEUE_DEFINITIONS = [
    {
        "key": "minutes",
        "queue": "queue:minutes",
        "label": "Minutas",
        "description": "Procesamiento principal de minutas y generación de contenido.",
        "consumer": "worker",
        "priority": "Alta",
        "threshold_attr": "minutes_queue_warning_threshold",
        "monitor_attr": "monitor_minutes_queue_enabled",
        "job_types": ["generate_minute"],
        "tag": "queue.minutes",
    },
    {
        "key": "email",
        "queue": "queue:email",
        "label": "Correo",
        "description": "Despacho de notificaciones y correos transaccionales.",
        "consumer": "worker",
        "priority": "Media",
        "threshold_attr": "email_queue_warning_threshold",
        "monitor_attr": "monitor_email_queue_enabled",
        "job_types": ["email"],
        "tag": "queue.email",
    },
    {
        "key": "maintenance",
        "queue": "queue:maintenance",
        "label": "Mantenimiento",
        "description": "Rutinas de limpieza, tareas técnicas y jobs operativos de fondo.",
        "consumer": "worker",
        "priority": "Baja",
        "threshold_attr": "maintenance_queue_warning_threshold",
        "monitor_attr": "monitor_maintenance_queue_enabled",
        "job_types": ["db_backup", "cleanup_sessions", "cleanup_temp_files"],
        "tag": "queue.maintenance",
    },
    {
        "key": "pdf",
        "queue": "queue:pdf",
        "label": "PDF",
        "description": "Renderizado y publicación de artefactos PDF.",
        "consumer": "pdf-worker",
        "priority": "Alta",
        "threshold_attr": "pdf_queue_warning_threshold",
        "monitor_attr": "monitor_pdf_queue_enabled",
        "job_types": ["pdf_job"],
        "tag": "queue.pdf",
    },
    {
        "key": "dlq",
        "queue": "queue:dlq",
        "label": "DLQ",
        "description": "Trabajos que fallaron y quedaron apartados para revisión manual.",
        "consumer": "Manual / soporte",
        "priority": "Crítica",
        "threshold_attr": "dlq_warning_threshold",
        "monitor_attr": "monitor_dlq_enabled",
        "job_types": ["failed_jobs"],
        "tag": "queue.dlq",
    },
]

