FROM node:20-alpine

ENV TZ=America/Santiago

WORKDIR /app

RUN apk add --no-cache curl tzdata \
    && cp /usr/share/zoneinfo/America/Santiago /etc/localtime \
    && echo "America/Santiago" > /etc/timezone

COPY APP/volumes/frontend/package*.json ./
RUN npm ci --include=dev --no-audit --no-fund

COPY APP/volumes/frontend/ ./
RUN npm run build

ENV NODE_ENV=production

RUN chown -R node:node /app
USER node

EXPOSE 5173

CMD ["npm", "run", "preview"]
