// src/components/ui/icon/categories/baseIcons.js
import {
  FaBuilding,
  FaCalendar,
  FaClock,
  FaEye,
  FaFilter,
  FaFolder,
  FaFolderOpen,
  FaInbox,
  FaIndustry,
  FaMagnifyingGlass,
  FaSliders,
  FaTag,
  FaTags,
  FaUser,
  FaUsers,
  FaGear,
  FaSun,
  FaMoon,
  FaLocationDot,
  FaNetworkWired,
  FaClockRotateLeft
} from "react-icons/fa6";

export const baseIcons = {
  business: FaBuilding,
  calendar: FaCalendar,
  clock: FaClock,
  eye: FaEye,
  filter: FaFilter,
  folder: FaFolder,
  folderOpen: FaFolderOpen,
  inbox: FaInbox,
  industry: FaIndustry,
  search: FaMagnifyingGlass,
  sliders: FaSliders,
  FaSlidersH: FaSliders,
  tag: FaTag,
  tags: FaTags,
  user: FaUser,
  users: FaUsers,
  gear: FaGear,
  sun: FaSun,
  moon: FaMoon,

  // Compatibilidad con nombres Fa...
  FaBuilding,
  FaCalendar,
  FaClock,
  FaEye,
  FaFilter,
  FaFolder,
  FaFolderOpen,
  FaInbox,
  FaIndustry,
  FaMagnifyingGlass,
  FaSliders,
  FaTag,
  FaTags,
  FaUser,
  FaUsers,
  FaGear,
  FaSun,
  FaMoon,
  FaCalendarAlt: FaCalendar,
  location: FaLocationDot,
  FaLocationDot,
  FaClockRotateLeft: FaClock,
  history: FaClockRotateLeft,
  FaNetworkWired
};