from __future__ import annotations

from core.config import settings

BUCKET_CODE_INPUTS = "inputs_container"
BUCKET_CODE_JSON = "json_container"
BUCKET_CODE_PUBLISHED = "published_container"
BUCKET_CODE_DRAFT = "draft_container"

BUCKET_INPUTS = "minuetaitor-inputs"
BUCKET_JSON = "minuetaitor-json"
BUCKET_PUBLISHED = "minuetaitor-published"
BUCKET_DRAFT = "minuetaitor-draft"

ART_INPUT_TRANSCRIPT = "INPUT_TRANSCRIPT"
ART_INPUT_SUMMARY = "INPUT_SUMMARY"
ART_LLM_JSON_ORIG = "LLM_JSON_ORIGINAL"
ART_CANONICAL_JSON = "CANONICAL_JSON"

ART_STATE_ORIGINAL = "ORIGINAL"
ART_STATE_READY = "READY"
ART_STATE_FAILED = "FAILED"

RECORD_TYPE_MINUTE = "MINUTE"
RECORD_STATUS_IN_PROGRESS = "in-progress"
RECORD_STATUS_READY = "ready-for-edit"
RECORD_STATUS_LLM_FAILED = "llm-failed"
RECORD_STATUS_PROC_ERROR = "processing-error"
RECORD_STATUS_PENDING = "pending"
RECORD_STATUS_PREVIEW = "preview"
RECORD_STATUS_COMPLETED = "completed"
RECORD_STATUS_CANCELLED = "cancelled"
RECORD_STATUS_DELETED = "deleted"

VERSION_STATUS_SNAPSHOT = "snapshot"
VERSION_STATUS_FINAL = "final"

QUEUE_MINUTES = "queue:minutes"
QUEUE_PDF = "queue:pdf"

STATUSES_NO_CONTENT = {
    RECORD_STATUS_LLM_FAILED,
    RECORD_STATUS_PROC_ERROR,
    RECORD_STATUS_IN_PROGRESS,
}

VALID_TRANSITIONS: dict[str, set[str]] = {
    RECORD_STATUS_IN_PROGRESS: {RECORD_STATUS_CANCELLED},
    RECORD_STATUS_READY: {RECORD_STATUS_PENDING, RECORD_STATUS_CANCELLED, RECORD_STATUS_DELETED},
    RECORD_STATUS_PENDING: {RECORD_STATUS_PREVIEW, RECORD_STATUS_CANCELLED, RECORD_STATUS_DELETED},
    RECORD_STATUS_PREVIEW: {
        RECORD_STATUS_PENDING,
        RECORD_STATUS_COMPLETED,
        RECORD_STATUS_CANCELLED,
        RECORD_STATUS_DELETED,
    },
    RECORD_STATUS_CANCELLED: {RECORD_STATUS_DELETED},
    RECORD_STATUS_LLM_FAILED: {RECORD_STATUS_DELETED},
    RECORD_STATUS_PROC_ERROR: {RECORD_STATUS_DELETED},
    RECORD_STATUS_COMPLETED: set(),
    RECORD_STATUS_DELETED: set(),
}

PROMPT_FILE = getattr(settings, "openai_system_prompt", "system_prompt_v08.txt")

