FROM python:3.12-slim

WORKDIR /app

# tzdata requiere esto para no preguntar zona horaria interactivamente
ENV DEBIAN_FRONTEND=noninteractive

COPY APP/volumes/scheduler/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY APP/volumes/scheduler/app/ /app/

CMD ["python", "-u", "scheduler.py"]