FROM python:3.12-slim

WORKDIR /app

ENV TZ=America/Santiago \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

COPY APP/volumes/pdf-worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY APP/volumes/pdf-worker/app/ .

CMD ["watchmedo", "auto-restart", "--patterns=*.py;*.html", "--recursive", "--", "python", "main.py"]