FROM python:3.12-slim

WORKDIR /app

COPY APP/volumes/worker/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

RUN pip install --no-cache-dir watchdog

COPY APP/volumes/worker/app/ /app/

CMD ["python", "worker.py"]