FROM python:3.12-slim

WORKDIR /app

ENV TZ=America/Santiago \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

COPY APP/volumes/worker/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install --no-cache-dir watchdog

COPY APP/volumes/worker/app/ /app/

CMD ["python", "worker.py"]